Repository wecode-bootcamp-korea/20-Westagram-backend, pull requests merged in 2021-05, with the labels that each got.

#11 [20기 이승무] Mission 1 Django 초기 세팅
  students/seungmoo-lee/.gitignore
  students/seungmoo-lee/account/__init__.py
  students/seungmoo-lee/account/admin.py
  students/seungmoo-lee/account/apps.py
  students/seungmoo-lee/account/migrations/__init__.py
  students/seungmoo-lee/account/models.py
  students/seungmoo-lee/account/tests.py
  students/seungmoo-lee/account/views.py
  students/seungmoo-lee/manage.py
  students/seungmoo-lee/westagram/__init__.py
  students/seungmoo-lee/westagram/asgi.py
  students/seungmoo-lee/westagram/settings.py
  students/seungmoo-lee/westagram/urls.py
  students/seungmoo-lee/westagram/wsgi.py
Labels: Status: Accepted

#13 [20기 김하민] Mission 1 Django 초기 세팅
  students/hamin-Kim/.gitignore
  students/hamin-Kim/manage.py
  students/hamin-Kim/user/__init__.py
  students/hamin-Kim/user/admin.py
  students/hamin-Kim/user/apps.py
  students/hamin-Kim/user/migrations/__init__.py
  students/hamin-Kim/user/models.py
  students/hamin-Kim/user/tests.py
  students/hamin-Kim/user/views.py
  students/hamin-Kim/westagram/__init__.py
  students/hamin-Kim/westagram/asgi.py
  students/hamin-Kim/westagram/settings.py
  students/hamin-Kim/westagram/urls.py
  students/hamin-Kim/westagram/wsgi.py
Labels: Status: Accepted

#10 [20기 정운산] Mission1 Django 초기 셋팅
  .gitignore
  students/unsan-Jeong/.gitignore
  students/unsan-Jeong/manage.py
  students/unsan-Jeong/users/__init__.py
  students/unsan-Jeong/users/admin.py
  students/unsan-Jeong/users/apps.py
  students/unsan-Jeong/users/migrations/__init__.py
  students/unsan-Jeong/users/models.py
  students/unsan-Jeong/users/tests.py
  students/unsan-Jeong/users/views.py
  students/unsan-Jeong/westagram/__init__.py
  students/unsan-Jeong/westagram/asgi.py
  students/unsan-Jeong/westagram/settings.py
  students/unsan-Jeong/westagram/urls.py
  students/unsan-Jeong/westagram/wsgi.py
Labels: Status: Accepted

#14 [20기 김경래] Mission 1 Django 초기 세팅
  students/kyeongrae-kim/.gitignore
  students/kyeongrae-kim/manage.py
  students/kyeongrae-kim/requirements.txt
  students/kyeongrae-kim/user/__init__.py
  students/kyeongrae-kim/user/admin.py
  students/kyeongrae-kim/user/apps.py
  students/kyeongrae-kim/user/migrations/__init__.py
  students/kyeongrae-kim/user/models.py
  students/kyeongrae-kim/user/tests.py
  students/kyeongrae-kim/user/views.py
  students/kyeongrae-kim/westagram/__init__.py
  students/kyeongrae-kim/westagram/asgi.py
  students/kyeongrae-kim/westagram/settings.py
  students/kyeongrae-kim/westagram/urls.py
  students/kyeongrae-kim/westagram/wsgi.py
Labels: Status: Accepted

#20 [20기 최우석] Django 초기 셋팅
  students/wooseok-choi/.gitignore
  students/wooseok-choi/manage.py
  students/wooseok-choi/user/__init__.py
  students/wooseok-choi/user/admin.py
  students/wooseok-choi/user/apps.py
  students/wooseok-choi/user/migrations/__init__.py
  students/wooseok-choi/user/models.py
  students/wooseok-choi/user/tests.py
  students/wooseok-choi/user/views.py
  students/wooseok-choi/westagram/__init__.py
  students/wooseok-choi/westagram/asgi.py
  students/wooseok-choi/westagram/settings.py
  students/wooseok-choi/westagram/urls.py
  students/wooseok-choi/westagram/wsgi.py
Labels: Status: Accepted

#23 [20기 문성호][MISSION1] Django 초기 셋팅
  students/sungho-moon/.gitignore
  students/sungho-moon/manage.py
  students/sungho-moon/requirements.txt
  students/sungho-moon/user/__init__.py
  students/sungho-moon/user/admin.py
  students/sungho-moon/user/apps.py
  students/sungho-moon/user/migrations/__init__.py
  students/sungho-moon/user/models.py
  students/sungho-moon/user/tests.py
  students/sungho-moon/user/views.py
  students/sungho-moon/westagram/__init__.py
  students/sungho-moon/westagram/asgi.py
  students/sungho-moon/westagram/settings.py
  students/sungho-moon/westagram/urls.py
  students/sungho-moon/westagram/wsgi.py
Labels: Status: Accepted

#21 [20기 전현수] Mission1 Django 초기 셋팅
  students/hyunsoo-jeon/.gitignore
  students/hyunsoo-jeon/manage.py
  students/hyunsoo-jeon/user/__init__.py
  students/hyunsoo-jeon/user/admin.py
  students/hyunsoo-jeon/user/apps.py
  students/hyunsoo-jeon/user/migrations/__init__.py
  students/hyunsoo-jeon/user/models.py
  students/hyunsoo-jeon/user/tests.py
  students/hyunsoo-jeon/user/views.py
  students/hyunsoo-jeon/westagram/__init__.py
  students/hyunsoo-jeon/westagram/asgi.py
  students/hyunsoo-jeon/westagram/settings.py
  students/hyunsoo-jeon/westagram/urls.py
  students/hyunsoo-jeon/westagram/wsgi.py
Labels: Status: Accepted

#8 [20기 최준식] Django 초기 세팅
  students/junsikchoi/.gitignore
  students/junsikchoi/README.md
  students/junsikchoi/manage.py
  students/junsikchoi/requirements.txt
  students/junsikchoi/users/__init__.py
  students/junsikchoi/users/admin.py
  students/junsikchoi/users/apps.py
  students/junsikchoi/users/migrations/__init__.py
  students/junsikchoi/users/models.py
  students/junsikchoi/users/tests.py
  students/junsikchoi/users/views.py
  students/junsikchoi/westagram/__init__.py
  students/junsikchoi/westagram/asgi.py
  students/junsikchoi/westagram/settings.py
  students/junsikchoi/westagram/urls.py
  students/junsikchoi/westagram/wsgi.py
Labels: Status: Accepted

#31 [20기 양영건] Mission 1 Django 초기 세팅
  students/younggeon-yang/.gitignore
  students/younggeon-yang/manage.py
  students/younggeon-yang/requirements.txt
  students/younggeon-yang/user/__init__.py
  students/younggeon-yang/user/admin.py
  students/younggeon-yang/user/apps.py
  students/younggeon-yang/user/migrations/__init__.py
  students/younggeon-yang/user/models.py
  students/younggeon-yang/user/tests.py
  students/younggeon-yang/user/views.py
  students/younggeon-yang/westargram/__init__.py
  students/younggeon-yang/westargram/asgi.py
  students/younggeon-yang/westargram/settings.py
  students/younggeon-yang/westargram/urls.py
  students/younggeon-yang/westargram/wsgi.py
Labels: Status: Accepted

#18 [20기 최대환] [Mission 2] 회원가입 엔드포인트
  students/dae-hwan/user/__init__.py
  students/dae-hwan/user/admin.py
  students/dae-hwan/user/apps.py
  students/dae-hwan/user/migrations/0001_initial.py
  students/dae-hwan/user/migrations/__init__.py
  students/dae-hwan/user/models.py
  students/dae-hwan/user/tests.py
  students/dae-hwan/user/urls.py
  students/dae-hwan/user/views.py
  students/dae-hwan/westagram/settings.py
  students/dae-hwan/westagram/urls.py
Labels: Status: Accepted

#15 [20기 양미화] Mission 2 회원가입 엔드포인트 # 2
  students/mihwa-yang/users/migrations/0001_initial.py
  students/mihwa-yang/users/migrations/0002_auto_20210504_1046.py
  students/mihwa-yang/users/models.py
  students/mihwa-yang/users/urls.py
  students/mihwa-yang/users/views.py
  students/mihwa-yang/westagram/settings.py
  students/mihwa-yang/westagram/urls.py
Labels: Status: Accepted

#26 [20기 이승무] Mission 2 회원가입 엔드포인트
  students/seungmoo-lee/account/migrations/0001_initial.py
  students/seungmoo-lee/account/models.py
  students/seungmoo-lee/account/urls.py
  students/seungmoo-lee/account/validations.py
  students/seungmoo-lee/account/views.py
  students/seungmoo-lee/westagram/urls.py
Labels: Status: Accepted

#33 [20기 김경래] Mission 2 회원가입 엔드포인트
  students/kyeongrae-kim/user/migrations/0001_initial.py
  students/kyeongrae-kim/user/migrations/0002_auto_20210502_1423.py
  students/kyeongrae-kim/user/migrations/0003_auto_20210503_1505.py
  students/kyeongrae-kim/user/models.py
  students/kyeongrae-kim/user/urls.py
  students/kyeongrae-kim/user/views.py
  students/kyeongrae-kim/westagram/settings.py
  students/kyeongrae-kim/westagram/urls.py
Labels: Status: Accepted

#36 [20기 김하민] Mission 2 회원가입 엔드포인트
  students/hamin-Kim/user/migrations/0001_initial.py
  students/hamin-Kim/user/models.py
  students/hamin-Kim/user/urls.py
  students/hamin-Kim/user/views.py
  students/hamin-Kim/westagram/settings.py
  students/hamin-Kim/westagram/urls.py
Labels: Status: Accepted

#48 [20기 박은혜] Mission1 Django 초기 셋팅 #1
  students/eunhye-park/account/__init__.py
  students/eunhye-park/account/admin.py
  students/eunhye-park/account/apps.py
  students/eunhye-park/account/migrations/__init__.py
  students/eunhye-park/account/models.py
  students/eunhye-park/account/tests.py
  students/eunhye-park/account/views.py
  students/eunhye-park/manage.py
  students/eunhye-park/project_westagram/__init__.py
  students/eunhye-park/project_westagram/asgi.py
  students/eunhye-park/project_westagram/settings.py
  students/eunhye-park/project_westagram/urls.py
  students/eunhye-park/project_westagram/wsgi.py
  students/project_westagram/.gitignore
  students/project_westagram/account/__init__.py
  students/project_westagram/account/admin.py
  students/project_westagram/account/apps.py
  students/project_westagram/account/migrations/__init__.py
  students/project_westagram/account/models.py
  students/project_westagram/account/tests.py
  students/project_westagram/account/views.py
  students/project_westagram/manage.py
  students/project_westagram/project_westagram/__init__.py
  students/project_westagram/project_westagram/asgi.py
  students/project_westagram/project_westagram/settings.py
  students/project_westagram/project_westagram/urls.py
  students/project_westagram/project_westagram/wsgi.py
Labels: Status: Accepted

#22 [20기 최우석] [Mission 2] 회원가입 엔드포인트
  students/wooseok-choi/user/migrations/0001_initial.py
  students/wooseok-choi/user/migrations/0002_auto_20210504_0508.py
  students/wooseok-choi/user/models.py
  students/wooseok-choi/user/urls.py
  students/wooseok-choi/user/validate.py
  students/wooseok-choi/user/views.py
  students/wooseok-choi/westagram/urls.py
Labels: Status: Accepted

#42 [20기 김보현] Mission1 Django 초기 셋팅
  students/bohyun-Kim/accounts/__init__.py
  students/bohyun-Kim/accounts/admin.py
  students/bohyun-Kim/accounts/apps.py
  students/bohyun-Kim/accounts/migrations/__init__.py
  students/bohyun-Kim/accounts/models.py
  students/bohyun-Kim/accounts/tests.py
  students/bohyun-Kim/accounts/views.py
  students/bohyun-Kim/manage.py
  students/bohyun-Kim/westagram/__init__.py
  students/bohyun-Kim/westagram/asgi.py
  students/bohyun-Kim/westagram/settings.py
  students/bohyun-Kim/westagram/urls.py
  students/bohyun-Kim/westagram/wsgi.py
Labels: Status: Accepted

#17 [20기 정운산] [Mission 3] 로그인 엔드포인트
  packages-microsoft-prod.deb
  packages-microsoft-prod.deb.1
  students/unsan-Jeong/.gitignore
  students/unsan-Jeong/users/migrations/0001_initial.py
  students/unsan-Jeong/users/migrations/0002_users_create_time.py
  students/unsan-Jeong/users/migrations/0003_auto_20210501_0551.py
  students/unsan-Jeong/users/models.py
  students/unsan-Jeong/users/urls.py
  students/unsan-Jeong/users/views.py
  students/unsan-Jeong/westagram/urls.py
Labels: Status: Accepted

#32 [20기 최준식] [Mission 2] 회원가입 엔드포인트
  students/junsikchoi/requirements.txt
  students/junsikchoi/users/migrations/0001_initial.py
  students/junsikchoi/users/migrations/0002_auto_20210504_1925.py
  students/junsikchoi/users/migrations/0003_alter_user_password.py
  students/junsikchoi/users/models.py
  students/junsikchoi/users/urls.py
  students/junsikchoi/users/validators.py
  students/junsikchoi/users/views.py
  students/junsikchoi/utils.py
  students/junsikchoi/westagram/settings.py
  students/junsikchoi/westagram/urls.py
Labels: Status: Accepted, 필수 구현 사항

#34 [20기 최우석] Mission 3 로그인 엔드포인트
  students/wooseok-choi/user/migrations/0001_initial.py
  students/wooseok-choi/user/migrations/0002_alter_user_password.py
  students/wooseok-choi/user/migrations/0002_auto_20210504_0508.py
  students/wooseok-choi/user/models.py
  students/wooseok-choi/user/urls.py
  students/wooseok-choi/user/utils.py
  students/wooseok-choi/user/validate.py
  students/wooseok-choi/user/views.py
  students/wooseok-choi/westagram/settings.py
  students/wooseok-choi/westagram/urls.py
Labels: Status: Accepted

#39 [20기 신승호][Mission 2] 회원가입 엔드포인트
  students/seungho-shin/.gitignore
  students/seungho-shin/accounts/__init__.py
  students/seungho-shin/accounts/admin.py
  students/seungho-shin/accounts/apps.py
  students/seungho-shin/accounts/migrations/__init__.py
  students/seungho-shin/accounts/models.py
  students/seungho-shin/accounts/tests.py
  students/seungho-shin/accounts/views.py
  students/seungho-shin/manage.py
  students/seungho-shin/requirements.txt
  students/seungho-shin/user/__init__.py
  students/seungho-shin/user/admin.py
  students/seungho-shin/user/apps.py
  students/seungho-shin/user/migrations/0001_initial.py
  students/seungho-shin/user/migrations/0002_alter_signup_name.py
  students/seungho-shin/user/migrations/0003_auto_20210504_0246.py
  students/seungho-shin/user/migrations/0004_auto_20210504_0500.py
  students/seungho-shin/user/migrations/0005_alter_user_phone_number.py
  students/seungho-shin/user/migrations/__init__.py
  students/seungho-shin/user/models.py
  students/seungho-shin/user/tests.py
  students/seungho-shin/user/urls.py
  students/seungho-shin/user/validators.py
  students/seungho-shin/user/views.py
  students/seungho-shin/westagram/__init__.py
  students/seungho-shin/westagram/asgi.py
  students/seungho-shin/westagram/settings.py
  students/seungho-shin/westagram/urls.py
  students/seungho-shin/westagram/wsgi.py
Labels: Status: Accepted

#44 [20기 양영건] Mission 2 회원가입 기능
  students/younggeon-yang/user/migrations/0001_initial.py
  students/younggeon-yang/user/migrations/0002_auto_20210503_1228.py
  students/younggeon-yang/user/migrations/0003_auto_20210504_0933.py
  students/younggeon-yang/user/models.py
  students/younggeon-yang/user/urls.py
  students/younggeon-yang/user/validations.py
  students/younggeon-yang/user/views.py
  students/younggeon-yang/westargram/settings.py
  students/younggeon-yang/westargram/urls.py
Labels: Status: Accepted

#61 [20기 박은혜] [Mission 2] 회원가입 엔드포인트
  students/eunhye-park/account/migrations/0001_initial.py
  students/eunhye-park/account/models.py
  students/eunhye-park/account/urls.py
  students/eunhye-park/account/views.py
  students/eunhye-park/project_westagram/settings.py
  students/eunhye-park/project_westagram/urls.py
Labels: Status: Accepted

#57 [20기 문성호][MISSION2] 회원가입 end point
  students/sungho-moon/user/migrations/0001_initial.py
  students/sungho-moon/user/models.py
  students/sungho-moon/user/urls.py
  students/sungho-moon/user/views.py
  students/sungho-moon/westagram/urls.py
Labels: Status: Accepted

#59 [20기 최준식] MISSION 3: 로그인 엔드포인트 구현
  students/junsikchoi/requirements.txt
  students/junsikchoi/users/urls.py
  students/junsikchoi/users/views.py
  students/junsikchoi/utils.py
Labels: Status: 리뷰 요청
